package com.idea2strategy.trading.strategy.runtime.plan;

public enum ExecutionPlanLoadFailure {
    SNAPSHOT_NOT_FOUND,
    PLAN_NOT_LOCKED,
    PLAN_INTEGRITY_MISMATCH,
    PLAN_IDENTITY_MISMATCH,
    PLAN_SCHEMA_VERSION_MISMATCH,
    FEATURE_VERSION_MISMATCH,
    RUNTIME_INTEGRITY_MISMATCH,
    RUNTIME_IDENTITY_MISMATCH,
    RUNTIME_SCHEMA_VERSION_MISMATCH
}
