package com.idea2strategy.trading.application.port;
import com.idea2strategy.trading.application.corporateaction.CorporateActionApplicationResult;
import com.idea2strategy.trading.domain.corporateaction.ApprovedCorporateAction;
public interface CorporateActionStore{CorporateActionApplicationResult apply(ApprovedCorporateAction action);}
