package com.idea2strategy.trading.domain.shorting;

public enum ShortRiskReasonCode {
    FRACTIONAL_SHORT_INCREASE_NOT_ALLOWED,
    INSTRUMENT_NOT_BORROWABLE,
    INSTRUMENT_NOT_EASY_TO_BORROW,
    LOCATE_EVIDENCE_MISSING,
    INSUFFICIENT_BUYING_POWER,
    PORTFOLIO_RISK_LIMIT_EXCEEDED
}
