package com.idea2strategy.trading.strategy.runtime.warmup;

public enum WarmupFailure {
    SNAPSHOT_NOT_FOUND,
    MANIFEST_UNAVAILABLE,
    MANIFEST_SCHEMA_MISMATCH,
    MANIFEST_DATASET_HASH_MISMATCH,
    MANIFEST_OBJECT_SCHEMA_MISMATCH,
    MANIFEST_OBJECT_INTEGRITY_MISMATCH,
    REQUIREMENT_MISSING,
    REQUIREMENT_FEATURE_MISMATCH,
    REQUIREMENT_VERSION_MISMATCH,
    REQUIREMENT_RESOLUTION_MISMATCH,
    REQUIREMENT_MANIFEST_MISMATCH,
    REQUIREMENT_OBSERVATION_OUT_OF_RANGE,
    REQUIREMENT_OBSERVATION_DUPLICATE,
    REQUIREMENT_COVERAGE_INSUFFICIENT
}
