package com.idea2strategy.trading.strategy.runtime.revalidation;

public enum RevalidationReason {
    EVALUATION_MARKET_STATE_MISSING,
    MARKET_STATE_MISSING,
    MARKET_CHANGED,
    EVALUATION_POSITION_STATE_MISSING,
    POSITION_STATE_MISSING,
    POSITION_CHANGED,
    BUDGET_STATE_MISSING,
    BUDGET_CHANGED,
    RUNTIME_STATE_MISSING,
    RUNTIME_STATE_CHANGED,
    BOT_NOT_RUNNING
}
